pub mod string;
pub mod list;
pub mod map;
pub mod set;
pub mod math;
pub mod io;
pub mod net;
pub mod json;
pub mod time;
pub mod tensor;
pub mod random;
pub mod regex_mod;
pub mod fs;
pub mod crypto;
pub mod encoding;
pub mod uuid_mod;
pub mod process;
pub mod log;
pub mod http;
pub mod http_server;
pub mod tcp;
pub mod url;
pub mod stream;
pub mod term;
pub mod csv_mod;
pub mod collections;
pub mod iter_mod;
pub mod math_extended;
pub mod time_extended;
pub mod json_extended;

use crate::interpreter::environment::Environment;

/// Register all standard library functions.
pub fn register_all(env: &mut Environment) {
    string::register_string_methods(env);
    math::register_math(env);
    io::register_io(env);
    time::register_time(env);
    set::register_set_methods(env);
    list::register_list_methods(env);
    json::register_json(env);
    tensor::register_tensor(env);
    random::register(env);
    regex_mod::register(env);
    fs::register(env);
    crypto::register(env);
    encoding::register(env);
    uuid_mod::register(env);
    process::register(env);
    log::register(env);
    http::register(env);
    http_server::register(env);
    tcp::register(env);
    url::register(env);
    stream::register(env);
    term::register(env);
    csv_mod::register(env);
    collections::register(env);
    iter_mod::register(env);
    math_extended::register(env);
    time_extended::register(env);
    json_extended::register(env);
}
