use crate::parser::ast::*;

/// Generate CUDA PTX assembly from an @gpu function's AST.
pub fn generate_ptx(func: &FuncDef) -> String {
    let name = &func.name;
    let body_ptx = compile_body_to_ptx(&func.body);

    format!(
        r#"//
// Generated by Aether Compiler
// Kernel: {name}
//
.version 7.0
.target sm_70
.address_size 64

.visible .entry {name}(
    .param .u64 param_input,
    .param .u64 param_output,
    .param .u32 param_n
)
{{
    .reg .u32 %tid, %ntid, %ctaid, %idx, %n;
    .reg .u64 %addr_in, %addr_out, %off;
    .reg .f32 %val, %result;
    .reg .pred %p;

    // Thread index
    mov.u32 %tid, %tid.x;
    mov.u32 %ntid, %ntid.x;
    mov.u32 %ctaid, %ctaid.x;
    mad.lo.u32 %idx, %ctaid, %ntid, %tid;

    // Bounds check
    ld.param.u32 %n, [param_n];
    setp.ge.u32 %p, %idx, %n;
    @%p bra DONE;

    // Load input
    ld.param.u64 %addr_in, [param_input];
    ld.param.u64 %addr_out, [param_output];
    cvt.u64.u32 %off, %idx;
    shl.b64 %off, %off, 2;
    add.u64 %addr_in, %addr_in, %off;
    add.u64 %addr_out, %addr_out, %off;
    ld.global.f32 %val, [%addr_in];

    // Body
{body_ptx}

    // Store result
    st.global.f32 [%addr_out], %result;

DONE:
    ret;
}}
"#,
        name = name,
        body_ptx = body_ptx,
    )
}

fn compile_body_to_ptx(body: &FuncBody) -> String {
    match body {
        FuncBody::Expression(expr) => compile_expr_ptx(expr, "%result"),
        FuncBody::Block(stmts) => {
            let mut ptx = String::new();
            for stmt in stmts {
                if let StmtKind::Return(Some(expr)) = &stmt.kind {
                    ptx.push_str(&compile_expr_ptx(expr, "%result"));
                } else if let StmtKind::Expression(expr) = &stmt.kind {
                    ptx.push_str(&compile_expr_ptx(expr, "%result"));
                }
            }
            ptx
        }
    }
}

fn compile_expr_ptx(expr: &Expr, dest: &str) -> String {
    match &expr.kind {
        ExprKind::Binary { left, op, right } => {
            let mut ptx = String::new();
            ptx.push_str(&compile_expr_ptx(left, "%val"));
            ptx.push_str("    mov.f32 %result, %val;\n");
            // Store left in temp
            ptx.push_str("    .reg .f32 %tmp_left;\n");
            ptx.push_str("    mov.f32 %tmp_left, %result;\n");
            ptx.push_str(&compile_expr_ptx(right, "%val"));
            let op_str = match op {
                BinaryOp::Add => "add.f32",
                BinaryOp::Sub => "sub.f32",
                BinaryOp::Mul => "mul.f32",
                BinaryOp::Div => "div.approx.f32",
                _ => "add.f32",
            };
            ptx.push_str(&format!("    {} {}, %tmp_left, %val;\n", op_str, dest));
            ptx
        }
        ExprKind::Identifier(name) => {
            // Map parameter names to registers
            if name == "x" || name == "val" || name == "input" {
                format!("    mov.f32 {}, %val;\n", dest)
            } else {
                format!("    // load {}\n    mov.f32 {}, %val;\n", name, dest)
            }
        }
        ExprKind::FloatLiteral(f) => {
            format!("    mov.f32 {}, {:#010x}; // {}\n", dest,
                    (*f as f32).to_bits(), f)
        }
        ExprKind::IntLiteral(n) => {
            format!("    mov.f32 {}, {:#010x}; // {}\n", dest,
                    (*n as f32).to_bits(), n)
        }
        _ => format!("    // unsupported expr\n    mov.f32 {}, 0x00000000;\n", dest),
    }
}

/// Generate PTX for a simple element-wise add kernel.
pub fn generate_add_kernel() -> String {
    let func = FuncDef {
        name: "vector_add".to_string(),
        params: vec![],
        return_type: None,
        body: FuncBody::Expression(Expr {
            kind: ExprKind::Identifier("x".to_string()),
            span: crate::lexer::tokens::Span::new("".into(), 0, 0),
        }),
        is_async: false,
        is_static: false,
        decorators: vec![],
        access: AccessModifier::Pub,
        span: crate::lexer::tokens::Span::new("".into(), 0, 0),
    };
    generate_ptx(&func)
}
