use crate::parser::ast::*;

/// Generate ROCm HIP C++ code from an @gpu function's AST.
pub fn generate_hip(func: &FuncDef) -> String {
    let name = &func.name;
    let body_hip = compile_body_to_hip(&func.body);

    format!(
        r#"// Generated by Aether Compiler — ROCm HIP
// Kernel: {name}

#include <hip/hip_runtime.h>

__global__ void {name}(const float* input, float* output, int n) {{
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx >= n) return;
    float val = input[idx];
    {body_hip}
    output[idx] = result;
}}

void launch_{name}(const float* input, float* output, int n) {{
    int threads = 256;
    int blocks = (n + threads - 1) / threads;
    hipLaunchKernelGGL({name}, dim3(blocks), dim3(threads), 0, 0, input, output, n);
    hipDeviceSynchronize();
}}
"#,
        name = name,
        body_hip = body_hip,
    )
}

fn compile_body_to_hip(body: &FuncBody) -> String {
    match body {
        FuncBody::Expression(expr) => format!("float result = {};", compile_expr_hip(expr)),
        FuncBody::Block(stmts) => {
            let mut hip = String::new();
            for stmt in stmts {
                match &stmt.kind {
                    StmtKind::Return(Some(expr)) => {
                        hip.push_str(&format!("float result = {};", compile_expr_hip(expr)));
                    }
                    StmtKind::VarDecl { name, value: Some(expr), .. } => {
                        hip.push_str(&format!("float {} = {};\n    ", name, compile_expr_hip(expr)));
                    }
                    _ => {}
                }
            }
            if !hip.contains("result") {
                hip.push_str("float result = val;");
            }
            hip
        }
    }
}

fn compile_expr_hip(expr: &Expr) -> String {
    match &expr.kind {
        ExprKind::Binary { left, op, right } => {
            let l = compile_expr_hip(left);
            let r = compile_expr_hip(right);
            let op_str = match op {
                BinaryOp::Add => "+",
                BinaryOp::Sub => "-",
                BinaryOp::Mul => "*",
                BinaryOp::Div => "/",
                BinaryOp::Pow => return format!("powf({}, {})", l, r),
                _ => "+",
            };
            format!("({} {} {})", l, op_str, r)
        }
        ExprKind::Identifier(name) => name.clone(),
        ExprKind::FloatLiteral(f) => format!("{}f", f),
        ExprKind::IntLiteral(n) => format!("{}.0f", n),
        ExprKind::Call { callee, args } => {
            if let ExprKind::Identifier(fname) = &callee.kind {
                let arg_strs: Vec<String> = args.iter().map(|a| compile_expr_hip(&a.value)).collect();
                format!("{}({})", fname, arg_strs.join(", "))
            } else {
                "0.0f".to_string()
            }
        }
        _ => "0.0f".to_string(),
    }
}
