use crate::parser::ast::*;

/// Generate WebGPU WGSL compute shader from an @gpu function's AST.
pub fn generate_wgsl(func: &FuncDef) -> String {
    let name = &func.name;
    let body_wgsl = compile_body_to_wgsl(&func.body);

    format!(
        r#"// Generated by Aether Compiler — WebGPU WGSL
// Kernel: {name}

@group(0) @binding(0) var<storage, read> input: array<f32>;
@group(0) @binding(1) var<storage, read_write> output: array<f32>;

@compute @workgroup_size(256)
fn {name}(@builtin(global_invocation_id) gid: vec3<u32>) {{
    let idx = gid.x;
    if (idx >= arrayLength(&input)) {{
        return;
    }}
    let val = input[idx];
    {body_wgsl}
    output[idx] = result;
}}
"#,
        name = name,
        body_wgsl = body_wgsl,
    )
}

fn compile_body_to_wgsl(body: &FuncBody) -> String {
    match body {
        FuncBody::Expression(expr) => format!("let result = {};", compile_expr_wgsl(expr)),
        FuncBody::Block(stmts) => {
            let mut wgsl = String::new();
            for stmt in stmts {
                match &stmt.kind {
                    StmtKind::Return(Some(expr)) => {
                        wgsl.push_str(&format!("let result = {};", compile_expr_wgsl(expr)));
                    }
                    StmtKind::VarDecl { name, value: Some(expr), .. } => {
                        wgsl.push_str(&format!("let {} = {};\n    ", name, compile_expr_wgsl(expr)));
                    }
                    _ => {}
                }
            }
            if !wgsl.contains("result") {
                wgsl.push_str("let result = val;");
            }
            wgsl
        }
    }
}

fn compile_expr_wgsl(expr: &Expr) -> String {
    match &expr.kind {
        ExprKind::Binary { left, op, right } => {
            let l = compile_expr_wgsl(left);
            let r = compile_expr_wgsl(right);
            let op_str = match op {
                BinaryOp::Add => "+",
                BinaryOp::Sub => "-",
                BinaryOp::Mul => "*",
                BinaryOp::Div => "/",
                _ => "+",
            };
            format!("({} {} {})", l, op_str, r)
        }
        ExprKind::Identifier(name) => name.clone(),
        ExprKind::FloatLiteral(f) => format!("{:.6}", f),
        ExprKind::IntLiteral(n) => format!("{}.0", n),
        ExprKind::Call { callee, args } => {
            if let ExprKind::Identifier(fname) = &callee.kind {
                let arg_strs: Vec<String> = args.iter().map(|a| compile_expr_wgsl(&a.value)).collect();
                format!("{}({})", fname, arg_strs.join(", "))
            } else {
                "0.0".to_string()
            }
        }
        _ => "0.0".to_string(),
    }
}
